[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
